/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.prac2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.*;

class AppTest {
    @Test
    public void testTask5() {
        // Test cases
        int[] sortedArray = {1, 2, 3, 4, 5};       // True
        int[] unsortedArray = {1, 3, 2, 4, 5};     // False
        int[] singleElementArray = {42};           // True
        int[] emptyArray = {};                     // True
        int[] nullArray = null;                    // True
        
        // Assertions
        assertTrue(SimpleFunctions.Task5(sortedArray));  // should be true
        assertFalse(SimpleFunctions.Task5(unsortedArray));  // should be false
        assertTrue(SimpleFunctions.Task5(singleElementArray));  // should be true
        assertTrue(SimpleFunctions.Task5(emptyArray));  // should be true
        assertTrue(SimpleFunctions.Task5(nullArray));  // should be true
    }

    public void testTask4() {
        // Test cases
        List<Integer> list1 = Arrays.asList(3, 4, 5, 6);
        List<Integer> list2 = Arrays.asList(5, 8, 9, 10);
        List<Integer> expectedResult = Arrays.asList(30, 36, 40, 30);

        List<Integer> result = SimpleFunctions.task4(list1, list2);
        assertEquals(expectedResult, result);

        // Test case with different length lists
        List<Integer> list3 = Arrays.asList(1, 2, 3);
        List<Integer> list4 = Arrays.asList(4, 5, 6, 7);

        assertNull(SimpleFunctions.task4(list3, list4));
    }

    public void testTask1() {
        int[] a = {1, 2, 3, 4, 5};
        int[] b = {0, 2, 4}; // Indexes to consider from array a

        int result = SimpleFunctions.Task1(a, b);

        // Calculate the expected sum manually
        int expectedSum = a[0] + a[2] + a[4];

        // Assert that the result matches the expected sum
        assertEquals(expectedSum, result);
    }


}
